package com.laranyman.eighteen.daytwo;

import org.junit.Test;

import static com.laranyman.eighteen.daytwo.DayTwo.checksumPartOne;
import static com.laranyman.eighteen.daytwo.DayTwo.checksumPartTwo;
import static org.junit.Assert.assertEquals;

/**
 * @author Lara
 */
public class DayTwoTest
{
    @Test
    public void testPartOneExampleOne ( )
    {
        String input = "abcdef\n" +
                       "bababc\n" +
                       "abbcde\n" +
                       "abcccd\n" +
                       "aabcdd\n" +
                       "abcdee\n" +
                       "ababab";
        assertEquals(12, checksumPartOne(input));
    }

    @Test
    public void testPartTwoExampleOne ( )
    {
        String input = "abcde\n" +
                       "fghij\n" +
                       "klmno\n" +
                       "pqrst\n" +
                       "fguij\n" +
                       "axcye\n" +
                       "wvxyz";

        assertEquals("fgij", checksumPartTwo(input));
    }

    @Test
    public void testPartOneActual ( )
    {
        String input = "xrysntkqrduheficajodiglvzw\n" +
                       "xzymntkqrbuhefmcajodiflvzw\n" +
                       "xpysetkyrbuhefmcajodiglvgw\n" +
                       "xtysnykqrbuhefmczjodiglvzw\n" +
                       "xpysntkqyvuhefmjajodiglvzw\n" +
                       "xpysntkqrbuqjfmcajodiglvzu\n" +
                       "xpysntkqrbuhefmvaoodimlvzw\n" +
                       "xplsntkqrbuhefmcajohimlvzw\n" +
                       "cpysntkqrbuhefmcajodiglpmw\n" +
                       "xpysndkqrbuhefmcajzdiglmzw\n" +
                       "xpysntkqrbuhsfmctjoqiglvzw\n" +
                       "xpysztkkrbuhewmcajodiglvzw\n" +
                       "xpysntkguzuhefmcajodiglvzw\n" +
                       "xpysnbkvrbuhyfmcajodiglvzw\n" +
                       "xpgsntkqrbphefmcajodzglvzw\n" +
                       "xpysntkqrbdhefmcajodvgqvzw\n" +
                       "xpmsntkqrbuhedmcajodiglvnw\n" +
                       "wpysntkqmbuheemcajodiglvzw\n" +
                       "xpysntdvrbuhdfmcajodiglvzw\n" +
                       "xpbsetkqrbuhefmcayodiglvzw\n" +
                       "xpasntkqrbuhefmcajydigovzw\n" +
                       "xpylntkqrbuhefmcajudiglnzw\n" +
                       "xpysqtkqrbuoefmcrjodiglvzw\n" +
                       "xlysntkqrbuhefmuejodiglvzw\n" +
                       "xpysntkqrzuhewmcajodaglvzw\n" +
                       "xpysotkqrbuhefmxajowiglvzw\n" +
                       "xpysntkqrbuhefmcajodinlyza\n" +
                       "xpysntkqrbuhemmmajofiglvzw\n" +
                       "xpysntkqcbuhezmcyjodiglvzw\n" +
                       "xpysntyqrbuhefmcajodiglvfn\n" +
                       "xpysntkqrbudefmcarodcglvzw\n" +
                       "xpysntkqrjuhefkcajodiglvzg\n" +
                       "xpysntkqrbuhefmcahooiglvow\n" +
                       "xpysntkqrqfhevmcajodiglvzw\n" +
                       "xpysntlqrbuhefmcajodivlvzu\n" +
                       "xpyjotkqrbuhefmcavodiglvzw\n" +
                       "xpysntqqrbuhebmcgjodiglvzw\n" +
                       "xpjsnikqbbuhefmcajodiglvzw\n" +
                       "xpysntkqrbuhefmcalodeflvzw\n" +
                       "xpysntktrbuhefmcaqoviglvzw\n" +
                       "xpysntkqrbuhefmcrjogiglvzk\n" +
                       "xpysntkqrjuhekmcajodixlvzw\n" +
                       "xpypntyqrbuhefmcajodigzvzw\n" +
                       "cpysnwkqrbuhefmcajodiglvww\n" +
                       "xpysntkqqbuqefmcajodiglvlw\n" +
                       "xpysntkqrbuhvfmcajldiglvzh\n" +
                       "xpysntkqrbuhefmzmjodislvzw\n" +
                       "xpysnnkqrbuhefmcajodjplyzw\n" +
                       "xpysntdqobuhefmcajbdiglvzw\n" +
                       "xpyzntknrbuhefmcajodigtvzw\n" +
                       "xpysntkqbbohefmcajodialvzw\n" +
                       "xpysntkqryuhefmcayoxiglvzw\n" +
                       "xxysntkqrbuhefmcajodiglgzl\n" +
                       "jzysntkqrbuhmfmcajodiglvzw\n" +
                       "xpysntocrbuhefmcakodiglvzw\n" +
                       "xpysntkqrbuheomrgjodiglvzw\n" +
                       "xpysntkerbuhefmxajoduglvzw\n" +
                       "xpysntkqobuhefpcajodiglvzd\n" +
                       "xpysntkqrbvhefmcajopislvzw\n" +
                       "xpysntkqrbuhefucqjodiglvqw\n" +
                       "xpysvtkqrbuhdfmcajokiglvzw\n" +
                       "xqysnjkqrbuhemmcajodiglvzw\n" +
                       "xpysnteqxbuhefmcajodiglvdw\n" +
                       "xpysntkqrbuhefzcajodignvzc\n" +
                       "xpysntkqrbuledmcajoyiglvzw\n" +
                       "xpysntkqrbuhofmcajkdigpvzw\n" +
                       "xpysmtkqrbuhefmcajodaglvze\n" +
                       "xlysntiqrbuhefmqajodiglvzw\n" +
                       "xpysntvqrbugefmcajodiglizw\n" +
                       "xpysntkqrbuhefmuwjndiglvzw\n" +
                       "ypysntkqrbuhefmbajodislvzw\n" +
                       "xpycntkqrbuhemmcaqodiglvzw\n" +
                       "xpysntkqrbuhefmcajobivdvzw\n" +
                       "xpysnfkprbuhefmcajodiglvkw\n" +
                       "xtysntkwrjuhefmcajodiglvzw\n" +
                       "xpysntkqrbqhefmcaxodiulvzw\n" +
                       "xpysntkqrbuhefmcajsdigkvkw\n" +
                       "xpysnekqrbugefmcajwdiglvzw\n" +
                       "xpysntkqjbuhefmcajoduglbzw\n" +
                       "xpysntkqrbohlfmcajodiggvzw\n" +
                       "xpysntkqrbfhefmcajodiglhnw\n" +
                       "xpmsntkirbusefmcajodiglvzw\n" +
                       "xpnsntkqrbehefmcajodigrvzw\n" +
                       "xpytntgqrbuhefmcajodigllzw\n" +
                       "xpysntkqrbuhefmcejodiglvvm\n" +
                       "xpyvntkqrbuhefmmajodiglmzw\n" +
                       "rpysntkirbuhefmcajodiglyzw\n" +
                       "xpysntkqrbuhefmcajoznglvzz\n" +
                       "xpysntkqrbmhefmcafodigwvzw\n" +
                       "xpysntkqrbuhetmcarodiglvzx\n" +
                       "xpysntnqrbuhefmcajogiglfzw\n" +
                       "xpysutkqjbuheomcajodiglvzw\n" +
                       "xpysnqkprbuhefkcajodiglvzw\n" +
                       "xpysntuqrbuhemmcajodyglvzw\n" +
                       "spysntkqrbupefmcajodigpvzw\n" +
                       "qpygntkqrbuhefmcajodqglvzw\n" +
                       "xpysnteqrbuhefmcatodiylvzw\n" +
                       "xpysntkqrbusefsckjodiglvzw\n" +
                       "xpysntkqrbubeflcajodiglvcw\n" +
                       "xpysntwqrbuhefmcajodigekzw\n" +
                       "xpysntkqrbuhefmcnjodiguvtw\n" +
                       "xpysntkqrbqhefmkasodiglvzw\n" +
                       "xmysntkqrbuhefmkcjodiglvzw\n" +
                       "xpysntkqrquhefmcajodiouvzw\n" +
                       "xpysnnkqrbuhefmcajodiplyzw\n" +
                       "xpysntkorbuhefaqajodiglvzw\n" +
                       "npysntkqobuhefmcajodiglvfw\n" +
                       "xlysntkqrbuhefmcazbdiglvzw\n" +
                       "xpysftkqrbihefmcajodiglezw\n" +
                       "xpysolqqrbuhefmcajodiglvzw\n" +
                       "xpysntkqrwuheixcajodiglvzw\n" +
                       "xoysntkqibuhefmcqjodiglvzw\n" +
                       "xpysntkqrbupefmcajodtulvzw\n" +
                       "xpyentkqrbuhvfmcajudiglvzw\n" +
                       "xpysntksrbuhefmgajodqglvzw\n" +
                       "xpysntkqrbuhcfmcvjodigldzw\n" +
                       "gpyrntdqrbuhefmcajodiglvzw\n" +
                       "vpysntvqrbuhefmcajndiglvzw\n" +
                       "xpvsntkqrbuhefvcajhdiglvzw\n" +
                       "xpysntkqrbubefmcajowiglvzl\n" +
                       "xpysndkqibuhefmcajodiblvzw\n" +
                       "xpysntkqrbuhefmldjodjglvzw\n" +
                       "xpysntzqrbuhefmcyjomiglvzw\n" +
                       "xpysntkqrbuhefmedjodiwlvzw\n" +
                       "xpysntklrbuhefmcyjodiglvjw\n" +
                       "xpypnlkqrbehefmcajodiglvzw\n" +
                       "xpysntkqrbuhefycacodiglvzz\n" +
                       "ypysntkqrbuhefmcajadiglvew\n" +
                       "xpysntkqobuhefmcajadiglhzw\n" +
                       "xpysbtxlrbuhefmcajodiglvzw\n" +
                       "xpysntkqrbuhefdcajoviglvww\n" +
                       "xpysntkqrbuhefmcaaodiblvzc\n" +
                       "wpysntkqrbuhefmcajddiglvbw\n" +
                       "wpysntmqrbuhefmcajodiglvza\n" +
                       "epysntkqrbuhemmcajoniglvzw\n" +
                       "vpysntkqrbuhejmcajodiglvzo\n" +
                       "xpysntkqrbuhebmmajodiglazw\n" +
                       "lpysntkqrguhtfmcajodiglvzw\n" +
                       "xpksndkqpbuhefmcajodiglvzw\n" +
                       "xpydnukqrbuhefmcajmdiglvzw\n" +
                       "xpysnmkqrbuhefioajodiglvzw\n" +
                       "xpysntkqruuhefmcajodyglvzx\n" +
                       "xpysntkqrmuhefmcmjidiglvzw\n" +
                       "xpysntksrbupefmcajodiplvzw\n" +
                       "xpykntkqrbuhefmmajodiglxzw\n" +
                       "xpssntkqrbuhefmzajodiglvgw\n" +
                       "xpysntkqrbuhefmcrjodigovzd\n" +
                       "xpysntkqrbuhefmpajodirlvqw\n" +
                       "xpysnskqrruhefmtajodiglvzw\n" +
                       "xpysnzkqrbuhezmcajodiglvzj\n" +
                       "xpysntkcrburefmckjodiglvzw\n" +
                       "xpysntkqrbuhefecpoodiglvzw\n" +
                       "xpysnjkqrbuhexmcajodigrvzw\n" +
                       "xpysztkqhbuhefmcanodiglvzw\n" +
                       "xpysntkqrbuhefmcajozyelvzw\n" +
                       "xpyuntkmrbuhefmcajodigcvzw\n" +
                       "xpysnykmrbuhefmaajodiglvzw\n" +
                       "jpysntkqrbuhefmcajodigumzw\n" +
                       "xtysntkqhbuhefmcajodiglvzz\n" +
                       "xpysntkqrbqhefmcxjouiglvzw\n" +
                       "xpysntkqreujefmmajodiglvzw\n" +
                       "xnysntzqrbuhefacajodiglvzw\n" +
                       "xpysntkqriuhefmcajkdiqlvzw\n" +
                       "xposntkqrbuheffcajodihlvzw\n" +
                       "xpysntkqpquhefmcajodrglvzw\n" +
                       "xpysjtkqrbudefmcajouiglvzw\n" +
                       "xpysnxkqrbulefmcacodiglvzw\n" +
                       "xpygntkqrbuhefmfajzdiglvzw\n" +
                       "xpysntkqrbuhefmuayodiglyzw\n" +
                       "xpysnbksrbuhefmcajediglvzw\n" +
                       "xkyzntkqrbuhefmcajodiglvzz\n" +
                       "xpysntkqrbehlxmcajodiglvzw\n" +
                       "xpysntkqryuhefmcaxodiklvzw\n" +
                       "xpysntdqrbuhefmcjjodiglvzt\n" +
                       "xpysntkqrbuhefmcauodigqvzy\n" +
                       "xpysftkqrbuhefmcajodrgvvzw\n" +
                       "xpysntkqrbuhefmczjodiglivw\n" +
                       "xpysatkorbuhefmcyjodiglvzw\n" +
                       "xhysntkqrbthefmcajodxglvzw\n" +
                       "xpysnpkqrbuhefmcajoqyglvzw\n" +
                       "xpyyntkqrbuhefmcjjodxglvzw\n" +
                       "xpysntkqrozhefhcajodiglvzw\n" +
                       "xpymftkqrbuhefmcajodiglvzo\n" +
                       "xpysntkqrbuhvfmcajodiyllzw\n" +
                       "xpysatsqrbuhefmcajodiglvzo\n" +
                       "cpysntkqqbuhefmcajodlglvzw\n" +
                       "xpysntkyrblhefmcajodiglvzz\n" +
                       "xpysntkfrbuhefbcajodiglbzw\n" +
                       "upysotkqrbuhpfmcajodiglvzw\n" +
                       "xpysdokqrbuheflcajodiglvzw\n" +
                       "xrysntkqrbuhefpcanodiglvzw\n" +
                       "xdysntkqrbuhefpcajodiglmzw\n" +
                       "xpyynteqrbjhefmcajodiglvzw\n" +
                       "xpysntkqrbuhefkcajodielvhw\n" +
                       "xplsktkqrbuhefmcajodtglvzw\n" +
                       "xpysrtkqrbuhefmcdjodiglvzx\n" +
                       "upysntkmrbuhefmcajodiglvzt\n" +
                       "xnysnpkqrbusefmcajodiglvzw\n" +
                       "xtysntnqrbuhexmcajodiglvzw\n" +
                       "xpysngkmrbfhefmcajodiglvzw\n" +
                       "xpysnhkhrbuhefmcajodiplvzw\n" +
                       "xpysntvqrbuhefmcaoodsglvzw\n" +
                       "xpyzntkqrbuhefmcajlviglvzw\n" +
                       "xpysndkqrbuievmcajodiglvzw\n" +
                       "xpysntkqrsuhcfzcajodiglvzw\n" +
                       "xpysntkqlbuhefmcajjdlglvzw\n" +
                       "xpysntkqrbuhifmcajoliylvzw\n" +
                       "xpysntkqxbphefmcajodialvzw\n" +
                       "bnyswtkqrbuhefmcajodiglvzw\n" +
                       "upysatkqrbuhefmcajodvglvzw\n" +
                       "xpysntkqqbuhefmcajodxglzzw\n" +
                       "xpysntkqryuhefmcafodinlvzw\n" +
                       "xpzsntkqrcuhefmcajokiglvzw\n" +
                       "xpynntkqrbuheimccjodiglvzw\n" +
                       "xpysnfkqduuhefmcajodiglvzw\n" +
                       "xpywntkqrbuhefmcajodigllzz\n" +
                       "xpysftkqrbahefmcajsdiglvzw\n" +
                       "xpysntkkrbutefmcljodiglvzw\n" +
                       "xfysntkqrbbhkfmcajodiglvzw\n" +
                       "xpysgtksrbuhefkcajodiglvzw\n" +
                       "xpysntyqrbuhefmcajodijlvzg\n" +
                       "xpysnpkqobuhefmcljodiglvzw\n" +
                       "xvysntkqrbuhefmcsjodiclvzw\n" +
                       "xpysntkqrtuhwfmcajodillvzw\n" +
                       "xpysntkprbuhejmcajouiglvzw\n" +
                       "apysntkqrbuhefmcaboviglvzw\n" +
                       "xpysqykqrbuhefmcajodirlvzw\n" +
                       "xpysntkqrluhefmcajowiglvzf\n" +
                       "dpysnokqrbuhefmcajoaiglvzw\n" +
                       "xppsntkqmbuheumcajodiglvzw\n" +
                       "xpysntkqrbuhlymcaoodiglvzw\n" +
                       "dpysntkqrbuhmfmcajodiglvzt\n" +
                       "xpysltbqrbuhefmcajoliglvzw\n" +
                       "xpysntpqrbuhefmcnjoniglvzw\n" +
                       "xpysntpqrbuhektcajodiglvzw\n" +
                       "xpysntkhrbshefmqajodiglvzw\n" +
                       "zpysntuqrbuhefmcajmdiglvzw\n" +
                       "xpysxtdqrbuhefmcajoyiglvzw\n" +
                       "xpysntkubbumefmcajodiglvzw\n" +
                       "xpysntkqzouhefmcajsdiglvzw\n" +
                       "xpysntkqrbuhefmcojoziglvyw\n" +
                       "jpysntkqrmuhefmcajodidlvzw\n" +
                       "xpmsttkqrhuhefmcajodiglvzw\n" +
                       "xpysntkqlbuhefmcajgdiflvzw\n" +
                       "xpysntxkrbuhefmcauodiglvzw\n" +
                       "xpysotkqubuhefscajodiglvzw\n" +
                       "xjysntkqrbvheemcajodiglvzw\n" +
                       "xpykntkqrbuhefmcpjodiglvow\n" +
                       "xplsntkqrbuvefmcajediglvzw\n" +
                       "upysntwqrbuhefmfajodiglvzw";

        System.out.println ( "Answer part one : " + checksumPartOne(input));
    }
    @Test
    public void testPartTwoActual ( )
    {
        String input = "xrysntkqrduheficajodiglvzw\n" +
                       "xzymntkqrbuhefmcajodiflvzw\n" +
                       "xpysetkyrbuhefmcajodiglvgw\n" +
                       "xtysnykqrbuhefmczjodiglvzw\n" +
                       "xpysntkqyvuhefmjajodiglvzw\n" +
                       "xpysntkqrbuqjfmcajodiglvzu\n" +
                       "xpysntkqrbuhefmvaoodimlvzw\n" +
                       "xplsntkqrbuhefmcajohimlvzw\n" +
                       "cpysntkqrbuhefmcajodiglpmw\n" +
                       "xpysndkqrbuhefmcajzdiglmzw\n" +
                       "xpysntkqrbuhsfmctjoqiglvzw\n" +
                       "xpysztkkrbuhewmcajodiglvzw\n" +
                       "xpysntkguzuhefmcajodiglvzw\n" +
                       "xpysnbkvrbuhyfmcajodiglvzw\n" +
                       "xpgsntkqrbphefmcajodzglvzw\n" +
                       "xpysntkqrbdhefmcajodvgqvzw\n" +
                       "xpmsntkqrbuhedmcajodiglvnw\n" +
                       "wpysntkqmbuheemcajodiglvzw\n" +
                       "xpysntdvrbuhdfmcajodiglvzw\n" +
                       "xpbsetkqrbuhefmcayodiglvzw\n" +
                       "xpasntkqrbuhefmcajydigovzw\n" +
                       "xpylntkqrbuhefmcajudiglnzw\n" +
                       "xpysqtkqrbuoefmcrjodiglvzw\n" +
                       "xlysntkqrbuhefmuejodiglvzw\n" +
                       "xpysntkqrzuhewmcajodaglvzw\n" +
                       "xpysotkqrbuhefmxajowiglvzw\n" +
                       "xpysntkqrbuhefmcajodinlyza\n" +
                       "xpysntkqrbuhemmmajofiglvzw\n" +
                       "xpysntkqcbuhezmcyjodiglvzw\n" +
                       "xpysntyqrbuhefmcajodiglvfn\n" +
                       "xpysntkqrbudefmcarodcglvzw\n" +
                       "xpysntkqrjuhefkcajodiglvzg\n" +
                       "xpysntkqrbuhefmcahooiglvow\n" +
                       "xpysntkqrqfhevmcajodiglvzw\n" +
                       "xpysntlqrbuhefmcajodivlvzu\n" +
                       "xpyjotkqrbuhefmcavodiglvzw\n" +
                       "xpysntqqrbuhebmcgjodiglvzw\n" +
                       "xpjsnikqbbuhefmcajodiglvzw\n" +
                       "xpysntkqrbuhefmcalodeflvzw\n" +
                       "xpysntktrbuhefmcaqoviglvzw\n" +
                       "xpysntkqrbuhefmcrjogiglvzk\n" +
                       "xpysntkqrjuhekmcajodixlvzw\n" +
                       "xpypntyqrbuhefmcajodigzvzw\n" +
                       "cpysnwkqrbuhefmcajodiglvww\n" +
                       "xpysntkqqbuqefmcajodiglvlw\n" +
                       "xpysntkqrbuhvfmcajldiglvzh\n" +
                       "xpysntkqrbuhefmzmjodislvzw\n" +
                       "xpysnnkqrbuhefmcajodjplyzw\n" +
                       "xpysntdqobuhefmcajbdiglvzw\n" +
                       "xpyzntknrbuhefmcajodigtvzw\n" +
                       "xpysntkqbbohefmcajodialvzw\n" +
                       "xpysntkqryuhefmcayoxiglvzw\n" +
                       "xxysntkqrbuhefmcajodiglgzl\n" +
                       "jzysntkqrbuhmfmcajodiglvzw\n" +
                       "xpysntocrbuhefmcakodiglvzw\n" +
                       "xpysntkqrbuheomrgjodiglvzw\n" +
                       "xpysntkerbuhefmxajoduglvzw\n" +
                       "xpysntkqobuhefpcajodiglvzd\n" +
                       "xpysntkqrbvhefmcajopislvzw\n" +
                       "xpysntkqrbuhefucqjodiglvqw\n" +
                       "xpysvtkqrbuhdfmcajokiglvzw\n" +
                       "xqysnjkqrbuhemmcajodiglvzw\n" +
                       "xpysnteqxbuhefmcajodiglvdw\n" +
                       "xpysntkqrbuhefzcajodignvzc\n" +
                       "xpysntkqrbuledmcajoyiglvzw\n" +
                       "xpysntkqrbuhofmcajkdigpvzw\n" +
                       "xpysmtkqrbuhefmcajodaglvze\n" +
                       "xlysntiqrbuhefmqajodiglvzw\n" +
                       "xpysntvqrbugefmcajodiglizw\n" +
                       "xpysntkqrbuhefmuwjndiglvzw\n" +
                       "ypysntkqrbuhefmbajodislvzw\n" +
                       "xpycntkqrbuhemmcaqodiglvzw\n" +
                       "xpysntkqrbuhefmcajobivdvzw\n" +
                       "xpysnfkprbuhefmcajodiglvkw\n" +
                       "xtysntkwrjuhefmcajodiglvzw\n" +
                       "xpysntkqrbqhefmcaxodiulvzw\n" +
                       "xpysntkqrbuhefmcajsdigkvkw\n" +
                       "xpysnekqrbugefmcajwdiglvzw\n" +
                       "xpysntkqjbuhefmcajoduglbzw\n" +
                       "xpysntkqrbohlfmcajodiggvzw\n" +
                       "xpysntkqrbfhefmcajodiglhnw\n" +
                       "xpmsntkirbusefmcajodiglvzw\n" +
                       "xpnsntkqrbehefmcajodigrvzw\n" +
                       "xpytntgqrbuhefmcajodigllzw\n" +
                       "xpysntkqrbuhefmcejodiglvvm\n" +
                       "xpyvntkqrbuhefmmajodiglmzw\n" +
                       "rpysntkirbuhefmcajodiglyzw\n" +
                       "xpysntkqrbuhefmcajoznglvzz\n" +
                       "xpysntkqrbmhefmcafodigwvzw\n" +
                       "xpysntkqrbuhetmcarodiglvzx\n" +
                       "xpysntnqrbuhefmcajogiglfzw\n" +
                       "xpysutkqjbuheomcajodiglvzw\n" +
                       "xpysnqkprbuhefkcajodiglvzw\n" +
                       "xpysntuqrbuhemmcajodyglvzw\n" +
                       "spysntkqrbupefmcajodigpvzw\n" +
                       "qpygntkqrbuhefmcajodqglvzw\n" +
                       "xpysnteqrbuhefmcatodiylvzw\n" +
                       "xpysntkqrbusefsckjodiglvzw\n" +
                       "xpysntkqrbubeflcajodiglvcw\n" +
                       "xpysntwqrbuhefmcajodigekzw\n" +
                       "xpysntkqrbuhefmcnjodiguvtw\n" +
                       "xpysntkqrbqhefmkasodiglvzw\n" +
                       "xmysntkqrbuhefmkcjodiglvzw\n" +
                       "xpysntkqrquhefmcajodiouvzw\n" +
                       "xpysnnkqrbuhefmcajodiplyzw\n" +
                       "xpysntkorbuhefaqajodiglvzw\n" +
                       "npysntkqobuhefmcajodiglvfw\n" +
                       "xlysntkqrbuhefmcazbdiglvzw\n" +
                       "xpysftkqrbihefmcajodiglezw\n" +
                       "xpysolqqrbuhefmcajodiglvzw\n" +
                       "xpysntkqrwuheixcajodiglvzw\n" +
                       "xoysntkqibuhefmcqjodiglvzw\n" +
                       "xpysntkqrbupefmcajodtulvzw\n" +
                       "xpyentkqrbuhvfmcajudiglvzw\n" +
                       "xpysntksrbuhefmgajodqglvzw\n" +
                       "xpysntkqrbuhcfmcvjodigldzw\n" +
                       "gpyrntdqrbuhefmcajodiglvzw\n" +
                       "vpysntvqrbuhefmcajndiglvzw\n" +
                       "xpvsntkqrbuhefvcajhdiglvzw\n" +
                       "xpysntkqrbubefmcajowiglvzl\n" +
                       "xpysndkqibuhefmcajodiblvzw\n" +
                       "xpysntkqrbuhefmldjodjglvzw\n" +
                       "xpysntzqrbuhefmcyjomiglvzw\n" +
                       "xpysntkqrbuhefmedjodiwlvzw\n" +
                       "xpysntklrbuhefmcyjodiglvjw\n" +
                       "xpypnlkqrbehefmcajodiglvzw\n" +
                       "xpysntkqrbuhefycacodiglvzz\n" +
                       "ypysntkqrbuhefmcajadiglvew\n" +
                       "xpysntkqobuhefmcajadiglhzw\n" +
                       "xpysbtxlrbuhefmcajodiglvzw\n" +
                       "xpysntkqrbuhefdcajoviglvww\n" +
                       "xpysntkqrbuhefmcaaodiblvzc\n" +
                       "wpysntkqrbuhefmcajddiglvbw\n" +
                       "wpysntmqrbuhefmcajodiglvza\n" +
                       "epysntkqrbuhemmcajoniglvzw\n" +
                       "vpysntkqrbuhejmcajodiglvzo\n" +
                       "xpysntkqrbuhebmmajodiglazw\n" +
                       "lpysntkqrguhtfmcajodiglvzw\n" +
                       "xpksndkqpbuhefmcajodiglvzw\n" +
                       "xpydnukqrbuhefmcajmdiglvzw\n" +
                       "xpysnmkqrbuhefioajodiglvzw\n" +
                       "xpysntkqruuhefmcajodyglvzx\n" +
                       "xpysntkqrmuhefmcmjidiglvzw\n" +
                       "xpysntksrbupefmcajodiplvzw\n" +
                       "xpykntkqrbuhefmmajodiglxzw\n" +
                       "xpssntkqrbuhefmzajodiglvgw\n" +
                       "xpysntkqrbuhefmcrjodigovzd\n" +
                       "xpysntkqrbuhefmpajodirlvqw\n" +
                       "xpysnskqrruhefmtajodiglvzw\n" +
                       "xpysnzkqrbuhezmcajodiglvzj\n" +
                       "xpysntkcrburefmckjodiglvzw\n" +
                       "xpysntkqrbuhefecpoodiglvzw\n" +
                       "xpysnjkqrbuhexmcajodigrvzw\n" +
                       "xpysztkqhbuhefmcanodiglvzw\n" +
                       "xpysntkqrbuhefmcajozyelvzw\n" +
                       "xpyuntkmrbuhefmcajodigcvzw\n" +
                       "xpysnykmrbuhefmaajodiglvzw\n" +
                       "jpysntkqrbuhefmcajodigumzw\n" +
                       "xtysntkqhbuhefmcajodiglvzz\n" +
                       "xpysntkqrbqhefmcxjouiglvzw\n" +
                       "xpysntkqreujefmmajodiglvzw\n" +
                       "xnysntzqrbuhefacajodiglvzw\n" +
                       "xpysntkqriuhefmcajkdiqlvzw\n" +
                       "xposntkqrbuheffcajodihlvzw\n" +
                       "xpysntkqpquhefmcajodrglvzw\n" +
                       "xpysjtkqrbudefmcajouiglvzw\n" +
                       "xpysnxkqrbulefmcacodiglvzw\n" +
                       "xpygntkqrbuhefmfajzdiglvzw\n" +
                       "xpysntkqrbuhefmuayodiglyzw\n" +
                       "xpysnbksrbuhefmcajediglvzw\n" +
                       "xkyzntkqrbuhefmcajodiglvzz\n" +
                       "xpysntkqrbehlxmcajodiglvzw\n" +
                       "xpysntkqryuhefmcaxodiklvzw\n" +
                       "xpysntdqrbuhefmcjjodiglvzt\n" +
                       "xpysntkqrbuhefmcauodigqvzy\n" +
                       "xpysftkqrbuhefmcajodrgvvzw\n" +
                       "xpysntkqrbuhefmczjodiglivw\n" +
                       "xpysatkorbuhefmcyjodiglvzw\n" +
                       "xhysntkqrbthefmcajodxglvzw\n" +
                       "xpysnpkqrbuhefmcajoqyglvzw\n" +
                       "xpyyntkqrbuhefmcjjodxglvzw\n" +
                       "xpysntkqrozhefhcajodiglvzw\n" +
                       "xpymftkqrbuhefmcajodiglvzo\n" +
                       "xpysntkqrbuhvfmcajodiyllzw\n" +
                       "xpysatsqrbuhefmcajodiglvzo\n" +
                       "cpysntkqqbuhefmcajodlglvzw\n" +
                       "xpysntkyrblhefmcajodiglvzz\n" +
                       "xpysntkfrbuhefbcajodiglbzw\n" +
                       "upysotkqrbuhpfmcajodiglvzw\n" +
                       "xpysdokqrbuheflcajodiglvzw\n" +
                       "xrysntkqrbuhefpcanodiglvzw\n" +
                       "xdysntkqrbuhefpcajodiglmzw\n" +
                       "xpyynteqrbjhefmcajodiglvzw\n" +
                       "xpysntkqrbuhefkcajodielvhw\n" +
                       "xplsktkqrbuhefmcajodtglvzw\n" +
                       "xpysrtkqrbuhefmcdjodiglvzx\n" +
                       "upysntkmrbuhefmcajodiglvzt\n" +
                       "xnysnpkqrbusefmcajodiglvzw\n" +
                       "xtysntnqrbuhexmcajodiglvzw\n" +
                       "xpysngkmrbfhefmcajodiglvzw\n" +
                       "xpysnhkhrbuhefmcajodiplvzw\n" +
                       "xpysntvqrbuhefmcaoodsglvzw\n" +
                       "xpyzntkqrbuhefmcajlviglvzw\n" +
                       "xpysndkqrbuievmcajodiglvzw\n" +
                       "xpysntkqrsuhcfzcajodiglvzw\n" +
                       "xpysntkqlbuhefmcajjdlglvzw\n" +
                       "xpysntkqrbuhifmcajoliylvzw\n" +
                       "xpysntkqxbphefmcajodialvzw\n" +
                       "bnyswtkqrbuhefmcajodiglvzw\n" +
                       "upysatkqrbuhefmcajodvglvzw\n" +
                       "xpysntkqqbuhefmcajodxglzzw\n" +
                       "xpysntkqryuhefmcafodinlvzw\n" +
                       "xpzsntkqrcuhefmcajokiglvzw\n" +
                       "xpynntkqrbuheimccjodiglvzw\n" +
                       "xpysnfkqduuhefmcajodiglvzw\n" +
                       "xpywntkqrbuhefmcajodigllzz\n" +
                       "xpysftkqrbahefmcajsdiglvzw\n" +
                       "xpysntkkrbutefmcljodiglvzw\n" +
                       "xfysntkqrbbhkfmcajodiglvzw\n" +
                       "xpysgtksrbuhefkcajodiglvzw\n" +
                       "xpysntyqrbuhefmcajodijlvzg\n" +
                       "xpysnpkqobuhefmcljodiglvzw\n" +
                       "xvysntkqrbuhefmcsjodiclvzw\n" +
                       "xpysntkqrtuhwfmcajodillvzw\n" +
                       "xpysntkprbuhejmcajouiglvzw\n" +
                       "apysntkqrbuhefmcaboviglvzw\n" +
                       "xpysqykqrbuhefmcajodirlvzw\n" +
                       "xpysntkqrluhefmcajowiglvzf\n" +
                       "dpysnokqrbuhefmcajoaiglvzw\n" +
                       "xppsntkqmbuheumcajodiglvzw\n" +
                       "xpysntkqrbuhlymcaoodiglvzw\n" +
                       "dpysntkqrbuhmfmcajodiglvzt\n" +
                       "xpysltbqrbuhefmcajoliglvzw\n" +
                       "xpysntpqrbuhefmcnjoniglvzw\n" +
                       "xpysntpqrbuhektcajodiglvzw\n" +
                       "xpysntkhrbshefmqajodiglvzw\n" +
                       "zpysntuqrbuhefmcajmdiglvzw\n" +
                       "xpysxtdqrbuhefmcajoyiglvzw\n" +
                       "xpysntkubbumefmcajodiglvzw\n" +
                       "xpysntkqzouhefmcajsdiglvzw\n" +
                       "xpysntkqrbuhefmcojoziglvyw\n" +
                       "jpysntkqrmuhefmcajodidlvzw\n" +
                       "xpmsttkqrhuhefmcajodiglvzw\n" +
                       "xpysntkqlbuhefmcajgdiflvzw\n" +
                       "xpysntxkrbuhefmcauodiglvzw\n" +
                       "xpysotkqubuhefscajodiglvzw\n" +
                       "xjysntkqrbvheemcajodiglvzw\n" +
                       "xpykntkqrbuhefmcpjodiglvow\n" +
                       "xplsntkqrbuvefmcajediglvzw\n" +
                       "upysntwqrbuhefmfajodiglvzw";

        System.out.println ( "Answer part two : " + checksumPartTwo (input));
    }

}
